# Practice Machine Learning and deep Learning

In [1]:
# Load library which are required 
import pandas as pd
import numpy as np
from sklearn.linear_model import Perceptron

# load dataset iris data
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
X = iris.data[:,(2,3)]     # only extracted petal length and width
y = iris.target            # target output variable

In [3]:
# Actual dataset 
X,y

(array([[1.4, 0.2],
        [1.4, 0.2],
        [1.3, 0.2],
        [1.5, 0.2],
        [1.4, 0.2],
        [1.7, 0.4],
        [1.4, 0.3],
        [1.5, 0.2],
        [1.4, 0.2],
        [1.5, 0.1],
        [1.5, 0.2],
        [1.6, 0.2],
        [1.4, 0.1],
        [1.1, 0.1],
        [1.2, 0.2],
        [1.5, 0.4],
        [1.3, 0.4],
        [1.4, 0.3],
        [1.7, 0.3],
        [1.5, 0.3],
        [1.7, 0.2],
        [1.5, 0.4],
        [1. , 0.2],
        [1.7, 0.5],
        [1.9, 0.2],
        [1.6, 0.2],
        [1.6, 0.4],
        [1.5, 0.2],
        [1.4, 0.2],
        [1.6, 0.2],
        [1.6, 0.2],
        [1.5, 0.4],
        [1.5, 0.1],
        [1.4, 0.2],
        [1.5, 0.2],
        [1.2, 0.2],
        [1.3, 0.2],
        [1.4, 0.1],
        [1.3, 0.2],
        [1.5, 0.2],
        [1.3, 0.3],
        [1.3, 0.3],
        [1.3, 0.2],
        [1.6, 0.6],
        [1.9, 0.4],
        [1.4, 0.3],
        [1.6, 0.2],
        [1.4, 0.2],
        [1.5, 0.2],
        [1.4, 0.2],


# Solve and calculated accuracy with ANN perceptron model

In [9]:
per_clf = Perceptron(random_state=42, penalty='l1')
per_clf.fit(X,y)
ypred = per_clf.predict(X)
print('='*100)
print(ypred)
print('='*100)
from sklearn.metrics import accuracy_score
print('Accuracy : ',accuracy_score(y, ypred))
print('='*100)
print("Coeficienct : ",per_clf.coef_ )
print('='*100)
print('Intercept : ' , per_clf.intercept_)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 1 2 2 2 1 2 1 1 2 2 1 1 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Accuracy :  0.92
Coeficienct :  [[  2.295   6.695  -9.495  -4.795]
 [ 13.02  -36.12   11.32  -29.42 ]
 [-41.36  -37.26   57.86   56.96 ]]
Intercept :  [  1.  18. -26.]


In [5]:
X = iris.data[:,:]

per_clf = Perceptron(random_state=42)
per_clf.fit(X,y)
ypred = per_clf.predict(X)
print('='*100)
print(ypred)
print('='*100)
from sklearn.metrics import accuracy_score
print('Accuracy : ',accuracy_score(y, ypred))
print('='*100)
print("Coeficienct : ",per_clf.coef_ )
print('='*100)
print('Intercept : ' , per_clf.intercept_)

[0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0
 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]
Accuracy :  0.6133333333333333
Coeficienct :  [[  2.4   6.8  -9.6  -4.9]
 [ 22.1 -42.2  13.5 -44.5]
 [-42.  -33.8  48.9  51.8]]
Intercept :  [  1.  34. -22.]


# Machine Leaning
Logistic regression becouse of classification problem

In [13]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X,y)
model.predict(X)
print('Accuracy : ',accuracy_score(y, ypred))
print('='*100)
print("Coeficienct : ",per_clf.coef_ )
print('='*100)
print('Intercept : ' , per_clf.intercept_)

Accuracy :  0.92
Coeficienct :  [[  2.295   6.695  -9.495  -4.795]
 [ 13.02  -36.12   11.32  -29.42 ]
 [-41.36  -37.26   57.86   56.96 ]]
Intercept :  [  1.  18. -26.]


C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
